### ISSUE TITLE
Diferencia JRE  y JVM

### ISSUE THREAD

**Issue by ervinj1998** [Ilikef150s2/Java_From_Scratch#8]
- JRE – Java Runtime Environment (JRE): es un paquete de instalación que proporciona un entorno para ejecutar (no desarrollar) el programa Java (o la aplicación) en su máquina. JRE solo lo utilizan aquellos que solo desean ejecutar los Programas Java, es decir, los usuarios finales de su sistema.
- JVM – Java Virtual Machine (JVM): es una parte muy importante de JDK y JRE porque está contenida o incorporada en ambos. Cualquier programa Java que ejecute utilizando JRE o JDK entra en la JVM y la JVM es responsable de ejecutar el programa Java línea por línea, por lo que también se lo conoce como intérprete.

**Comment by Hawaiideveloper** [comment]
very good.   Please close this issue, then set the title to reflect "solved"

**Comment by ervinj1998** [comment]
Duda resuelta sobre archivo ejecutable en java
